from .sport import (
    SPORT_TABLE_NAME,
    CREATE_SPORT_TABLE_SQL,
    DROP_SPORT_TABLE_SQL,
)
from .buk import (
    BUK_TABLE_NAME,
    CREATE_BUK_TABLE_SQL,
    DROP_BUK_TABLE_SQL,
)
from .event import (
    EVENT_TABLE_NAME,
    CREATE_EVENT_TABLE_SQL,
    DROP_EVENT_TABLE_SQL,
)
from .market import (
    MARKET_TABLE_NAME,
    CREATE_MARKET_TABLE_SQL,
    DROP_MARKET_TABLE_SQL,
)
from .event_market import (
    EVENT_MARKET_TABLE_NAME,
    CREATE_EVENT_MARKET_TABLE_SQL,
    DROP_EVENT_MARKET_TABLE_SQL,
)
from .odd import (
    ODD_TABLE_NAME,
    CREATE_ODD_TABLE_SQL,
    DROP_ODD_TABLE_SQL,
)
from .event_group import (
    EVENT_GROUP_TABLE_NAME,
    CREATE_EVENT_GROUP_TABLE_SQL,
    DROP_EVENT_GROUP_TABLE_SQL,
)
from .event_group_fts5 import (
    EVENT_GROUP_FTS5_TABLE_NAME,
    CREATE_EVENT_FTS5_GROUP_TABLE_SQL,
    DROP_EVENT_GROUP_FTS5_TABLE_SQL,
)


CREATE_TABLES_SQL = [
    (SPORT_TABLE_NAME, CREATE_SPORT_TABLE_SQL),
    (EVENT_GROUP_TABLE_NAME, CREATE_EVENT_GROUP_TABLE_SQL),
    (EVENT_GROUP_FTS5_TABLE_NAME, CREATE_EVENT_FTS5_GROUP_TABLE_SQL),
    (BUK_TABLE_NAME, CREATE_BUK_TABLE_SQL),
    (EVENT_TABLE_NAME, CREATE_EVENT_TABLE_SQL),
    (MARKET_TABLE_NAME, CREATE_MARKET_TABLE_SQL),
    (EVENT_MARKET_TABLE_NAME, CREATE_EVENT_MARKET_TABLE_SQL),
    (ODD_TABLE_NAME, CREATE_ODD_TABLE_SQL),
]


DROP_TABLES_SQL = [
    (ODD_TABLE_NAME, DROP_ODD_TABLE_SQL),
    (EVENT_MARKET_TABLE_NAME, DROP_EVENT_MARKET_TABLE_SQL),
    (MARKET_TABLE_NAME, DROP_MARKET_TABLE_SQL),
    (EVENT_TABLE_NAME, DROP_EVENT_TABLE_SQL),
    (BUK_TABLE_NAME, DROP_BUK_TABLE_SQL),
    (EVENT_GROUP_FTS5_TABLE_NAME, CREATE_EVENT_FTS5_GROUP_TABLE_SQL),
    (EVENT_GROUP_TABLE_NAME, DROP_EVENT_GROUP_TABLE_SQL),
    (SPORT_TABLE_NAME, DROP_SPORT_TABLE_SQL),
]