MARKET_TABLE_NAME = 'market'

CREATE_MARKET_TABLE_SQL = '''
CREATE TABLE IF NOT EXISTS market(
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
)
'''

DROP_MARKET_TABLE_SQL = 'DROP TABLE IF EXISTS market'