SPORT_TABLE_NAME = 'sport'

CREATE_SPORT_TABLE_SQL = '''
CREATE TABLE IF NOT EXISTS sport(
    id      INTEGER     PRIMARY KEY,
    name    TEXT        UNIQUE NOT NULL
)
'''

DROP_SPORT_TABLE_SQL = 'DROP TABLE IF EXISTS sport'
